name: mahfel_ons
description: "اپلیکیشن محفل انس - آثار دکتر محمد شیروی خوزانی"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.2
  open_filex: ^4.3.2
  url_launcher: ^6.2.4
  syncfusion_flutter_pdfviewer: ^24.2.3  # این خط را حتماً اضافه کنید

flutter:
  uses-material-design: true
