name: mahfel_ons
description: اپلیکیشن محفل انس برای نمایش کانال‌های ایتا و دانلود فایل‌ها
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  http: ^1.2.0
  path_provider: ^2.1.0
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
