name: Build Mahfel Ons APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Project
        run: |
          # ۱. ساخت پروژه تمیز با ساختار مدرن فلاتر
          flutter create app_build --org ir.shiravi --project-name mahfel_ons --platforms=android
          cd app_build

          # ۲. جایگزینی کدهای برنامه
          cp ../pubspec.yaml ./pubspec.yaml
          cp ../main.dart lib/main.dart
          mkdir -p assets
          if [ -f ../logo.png ]; then cp ../logo.png assets/logo.png; else cp android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png assets/logo.png; fi

          # ۳. اضافه کردن مجوز اینترنت به مانیفست پیش‌فرض
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml

          # ۴. دانلود پکیج‌ها و ساخت نهایی APK
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mahfel-Ons-App
          path: app_build/build/app/outputs/flutter-apk/app-release.apk
